name: Docker build latest

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: qemu workaround
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: lss233/kirara-agent-framework:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max