name: 处理不活跃的 Issue 和 PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          # 基本配置
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60  # 60天不活跃标记为 stale
          days-before-close: 14  # 标记为 stale 后14天关闭
          
          # 友好的提示信息
          stale-issue-message: >
            👋 您好！这个 issue 已经 60 天没有活动了。
            
            为了保持我们的 issue 列表整洁，我们会标记长时间不活跃的 issue。
            如果您认为这个 issue 仍然重要且有效，请留下评论或移除 "stale" 标签，
            否则它将在 14 天后自动关闭。
            
            感谢您的理解和贡献！
          
          stale-pr-message: >
            👋 您好！这个 PR 已经 60 天没有活动了。
            
            为了保持我们的 PR 列表整洁，我们会标记长时间不活跃的 PR。
            如果您仍在处理这个 PR，请留下评论或移除 "stale" 标签，
            否则它将在 14 天后自动关闭。
            
            如果您需要帮助完成这个 PR，请告诉我们！
            
            感谢您的贡献！
          
          close-issue-message: >
            🙏 由于长时间没有活动，我们暂时关闭了这个 issue。
            
            如果您认为这个问题仍然存在，请随时重新打开或创建新的 issue。
            
            谢谢！
          
          close-pr-message: >
            🙏 由于长时间没有活动，我们暂时关闭了这个 PR。
            
            如果您想继续这项工作，请随时重新打开或创建新的 PR。
            
            感谢您的贡献！
          
          # 排除某些标签的 issue/PR
          exempt-issue-labels: 'planned,documentation,long-term-task'
          exempt-pr-labels: 'WIP,waiting-for-review,long-term-task'
          
          # 只处理某些标签的 issue/PR（可选）
          # only-labels: ''
          
          # 其他选项
          operations-per-run: 100  # 每次运行处理的最大数量
          remove-stale-when-updated: true  # 当更新时移除 stale 标签
          ascending: true  # 从最老的开始处理
